server:
  port: 9797
  servlet:    context-path: RegistrationApp

spring:  datasource:    driver-class-name: oracel.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: manager
  jpa:    hibernate:      ddl-auto: update
    generate-ddl: true
   